USE KamigamiNoTanjou

DROP TABLE IF EXISTS Magics;

CREATE TABLE Magics (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Description LONGTEXT NULL,
    
    CONSTRAINT PK_Magics PRIMARY KEY (ID)
) ENGINE=INNODB, CHARSET=utf8
;
