USE KamigamiNoTanjou;

DROP TABLE IF EXISTS LINK_CharacsMagics;

CREATE TABLE LINK_CharacsMagics(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Charac INT UNSIGNED NOT NULL,
    Magic INT UNSIGNED NOT NULL,
    `Rank` INT UNSIGNED NOT NULL,
    
    CONSTRAINT PK_LINK_CharacsMagics PRIMARY KEY (ID),
    CONSTRAINT FK_LINK_CharacsMagics_Charac FOREIGN KEY (Charac) REFERENCES Characs(ID),
    CONSTRAINT FK_LINK_CharacsMagics_Magic FOREIGN KEY (Magic) REFERENCES Magics(ID)
) ENGINE=INNODB, CHARSET=utf8
;
