USE KamigamiNoTanjou;

DROP TABLE IF EXISTS Elems;

CREATE TABLE Elems(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Illustration MEDIUMBLOB NOT NULL,
    
    CONSTRAINT PK_Elems PRIMARY KEY (ID)
) ENGINE=INNODB, CHARSET=utf8
;
