USE KamigamiNoTanjou;

DROP TABLE IF EXISTS LINK_ElemsMagics;

CREATE TABLE LINK_ElemsMagics(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Elem INT UNSIGNED NOT NULL,
    Magic INT UNSIGNED NOT NULL,
    
    CONSTRAINT PK_LINK_ElemsMagics PRIMARY KEY (ID),
    CONSTRAINT FK_LINK_ElemsMagics_Elem FOREIGN KEY (Elem) REFERENCES Elems(ID),
    CONSTRAINT FK_LINK_ElemsMagics_Magic FOREIGN KEY (Magic) REFERENCES Magics(ID)
) ENGINE=INNODB, CHARSET=utf8
;
