USE KntManagerProd;

DROP TABLE IF EXISTS FamilyStatuses;

CREATE TABLE FamilyStatuses(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,

    CONSTRAINT PK_FamilyStatuses PRIMARY KEY(ID)
) ENGINE=INNODB, CHARSET=utf8
;
