USE KntManagerProd;

DROP TABLE IF EXISTS Maps;

CREATE TABLE Maps(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(150) NOT NULL,
    EstablishmentDate DATETIME NULL,
    ExpiryDate DATETIME NULL,
    Nation INT UNSIGNED NULL,
    Content MEDIUMBLOB NOT NULL,

    CONSTRAINT PK_Maps PRIMARY KEY(ID),
    CONSTRAINT FK_Map_Nation FOREIGN KEY (Nation) REFERENCES Nations(ID)
) ENGINE=INNODB, CHARSET=utf8
;
