USE KamigamiNoTanjou;

DROP TABLE IF EXISTS Genders;

CREATE TABLE Genders(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,

    CONSTRAINT PK_Genders PRIMARY KEY(ID)
) ENGINE=INNODB, CHARSET=utf8
;
